Repository signaux-faibles/prepare-import, pull requests merged in 2020-04, with the labels that each got.

#11 fix: Correction des types incorrects + Retrait de récursion
  main.go
  main_test.go
Labels: bug

#14 feat: actication de DeepSource pour suivre la qualité de code
  .deepsource.toml
Labels: enhancement

#13 refactor: réduction de complexité + commentaires
  Makefile
  main.go
  main_test.go
  signauxfaiblesTypes.go
Labels: documentation, enhancement

#15 feat: Gestion d'erreurs
  main.go
  main_test.go
Labels: enhancement

#16 fix: ajout de commentaires (godoc) pour types et fonctions
  main.go
  signauxfaiblesTypes.go
Labels: documentation

#17 feat: Envoi de couverture de tests à Codacy
  .github/workflows/go.yml
Labels: enhancement

#18 fix: envoi de couverture de tests à DeepSource
  .github/workflows/go.yml
Labels: enhancement

#19 fix: Faux positifs sur remontée de fichiers non supportés
  main.go
  main_test.go
Labels: bug

#20 feat(tests): Ajout d'un test de bout en bout
  .github/workflows/go.yml
  README.md
  end_to_end_golden.txt
  end_to_end_test.go
  main.go
  main_test.go
Labels: enhancement

#21 feat: Support des fichiers textuels Diane
  README.md
  main_test.go
  signauxfaiblesTypes.go
Labels: documentation, enhancement

#22 feat: Vérification du flux d'erreurs, dans test de bout en bout
  end_to_end_golden_err.txt
  end_to_end_test.go
Labels: enhancement

#25 fix(style): Corrections de style de code recommandées par Codacy
  main.go
  main_test.go
  signauxfaiblesTypes.go
Labels: documentation, enhancement

#27 refactor: Correction de l'avertissement "unexported-return"
  main.go
  main_test.go
Labels: enhancement

#26 feat: Ajout du paramètre date_fin_effectif + typage des paramètres
  end_to_end_golden.txt
  end_to_end_golden_err.txt
  end_to_end_test.go
  main.go
  main_test.go
Labels: enhancement
