Repository signaux-faibles/prepare-import, pull requests merged in 2020-09, with the labels that each got.

#34 fix(#32): Les fichiers *.bin n'ont plus d'extension
  end_to_end_golden.txt
  end_to_end_test.go
  main.go
  main_test.go
  signauxfaiblesTypes.go
Labels: bug

#33 fix(#31): Les chemins d'accès de la propriété files doivent inclure le numéro de batch
  end_to_end_golden.txt
  end_to_end_golden_err.txt
  end_to_end_test.go
  main.go
  main_test.go
Labels: bug

#35 feat: Outils d'importation
  .gitignore
  tools/create_filter/main.go
  tools/create_filter/main_test.go
  tools/create_filter/test_data.csv
  tools/filter_to_diane.awk
  tools/filter_unprintable.sh
  tools/goupy.py
  tools/procedure_import.md
Labels: documentation, enhancement

#36 fix: Mise à jour des procédures de préparation à l'importation + formatage
  .github/workflows/go.yml
  Makefile
  README.md
  end_to_end_test.go
  tools/create_filter/main.go
  tools/procedure_import.md
Labels: documentation

#37 fix(github): "PR has only one non-merge commit and it's not semantic"
  .github/semantic.yml
Labels: enhancement
