Repository signaux-faibles/prepare-import, pull requests merged in 2020-03, with the labels that each got.

#1 Fix + refactor tests for PopulateFilesProperty
  main.go
  main_test.go
Labels: bug, enhancement

#2 feat(ci): run tests on GitHub Actions
  .github/workflows/go.yml
Labels: enhancement

#3 feat(ci): Ajout intégration continue GitHub Actions dans branche dev
  .github/workflows/go.yml
Labels: enhancement

#5 feat: `PrepareImport()` retourne une structure compatible avec Admin
  README.md
  main.go
  main_test.go
Labels: documentation, enhancement

#6 docs: Présentation générale
  .github/workflows/go.yml
  README.md
  main.go
Labels: documentation

#8 feat: prepare-import retourne les fichiers supportés dans un répertoire spécifié
  .github/workflows/go.yml
  main.go
  main_test.go
Labels: enhancement

#9 Feat: Prendre en charge fichiers csv courants
  main.go
  main_test.go
Labels: enhancement

#10 feat: Reconnaissance de certains fichiers reçus par goup
  main.go
  main_test.go
Labels: enhancement
